### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Visual-Rock** [fabiankachlock/uno-online#1]
Karten werden bei manchen Clients nicht richtig angezeigt und entfernt

Wenn spieler runde verlassen werden sie nicht zuverlässig gelöscht (negative spieler angezeigt)

Nicht alle spieler/karten werden angezeigt

**Comment by fabiankachlock** [comment]
https://github.com/fabiankachlock/one-online/blob/main/static/ts/game.ts#L162-L163

Dadurch, dass `.splice()` zweimal am selbem Array aufgerufen wurde, war bei zweiten Aufruf alles verschoben. Deswegen sind an anderen Stellen Errors aufgetreten und alles ging den Bach runter.
